<?xml version="1.0" encoding="utf-8" ?>
<wsdl:definitions 
    targetNamespace="http://stg.tu-darmstadt.de/ao4bpel"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:tns="http://stg.tu-darmstadt.de/ao4bpel"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
    xmlns:counter="http://stg.tu-darmstadt.de/counterService" >
        
	<import namespace="http://stg.tu-darmstadt.de/counterService" location="CounterService.wsdl"/>
          
	<plnk:partnerLinkType name="CounterServiceLinkType">
		<plnk:role name="counterService" portType="counter:CounterServicePortType"/>
	</plnk:partnerLinkType>

</wsdl:definitions>
